name: oc
services:
  dev-edk2:
    build:
      context: Dockerfiles/oc-dev
      target: oc-dev-edk2
    environment:
      - ARCHS
      - ARCHS_EXT
      - TARGETS
      - RTARGETS
      - TOOLCHAINS
      - SKIP_TESTS
      - SKIP_BUILD
      - SKIP_PACKAGE
      - BUILD_ARGUMENTS
    volumes:
      - ${PWD}:/com.docker.devenvironments.code
    working_dir: /com.docker.devenvironments.code
  dev-docs:
    build:
      context: Dockerfiles/oc-dev
      target: oc-dev-docs
    volumes:
      - ${PWD}:/com.docker.devenvironments.code
    working_dir: /com.docker.devenvironments.code
  build-oc:
    extends:
      service: dev-edk2
    entrypoint:
      - /bin/bash
      - -c
      - "{ . ~/.edk2_rc.sh && eval \"$$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh)\" && ./build_oc.tool ; } || exit 1"
  build-duet:
    extends:
      service: dev-edk2
    entrypoint:
      - /bin/bash
      - -c
      - "{ . ~/.edk2_rc.sh && eval \"$$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh)\" && ./build_duet.tool ; } || exit 1"
  build-docs:
    extends:
      service: dev-docs
    entrypoint:
      - /bin/bash
      - -c
      - "{ doxygen Doxyfile &> log.txt && cd Doxy/latex && make pdf &> log.txt ; } || { tail -200 log.txt ; exit 1 ; }"
