name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1

jobs:
  build-macos:
    name: macOS XCODE5
    # See https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source
    runs-on: macos-14
    env:
      JOB_TYPE: BUILD
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Toolchain
        run: |
          brew tap FiloSottile/homebrew-musl-cross
          brew install musl-cross

      - name: Install Dependencies
        run: brew install openssl mingw-w64

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - run: ./build_duet.tool
      - run: ./build_oc.tool

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS XCODE5 Artifacts
          path: Binaries/*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Binaries/*.zip
          tag: ${{ github.ref }}
          file_glob: true

  build-linux-clangpdb:
    name: Linux CLANGPDB
    runs-on: ubuntu-22.04
    env:
      TOOLCHAINS: CLANGPDB
    steps:
      - uses: actions/checkout@v4

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: ./build_duet.tool
        run: docker compose run build-duet

      - name: ./build_oc.tool
        run: docker compose run build-oc

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux CLANGPDB Artifacts
          path: Binaries/*.zip

  build-linux-gcc5:
    name: Linux GCC
    runs-on: ubuntu-22.04
    env:
      TOOLCHAINS: GCC
    steps:
      - uses: actions/checkout@v4

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: ./build_duet.tool
        run: docker compose run build-duet

      - name: ./build_oc.tool
        run: docker compose run build-oc

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux GCC Artifacts
          path: Binaries/*.zip

  build-linux-clangdwarf:
    name: Linux CLANGDWARF
    runs-on: ubuntu-22.04
    env:
      TOOLCHAINS: CLANGDWARF
    steps:
      - uses: actions/checkout@v4

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: ./build_duet.tool
        run: docker compose run build-duet

      - name: ./build_oc.tool
        run: docker compose run build-oc

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux CLANGDWARF Artifacts
          path: Binaries/*.zip

  build-linux-docs:
    name: Linux Docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: Docs
        run: docker compose run build-docs

  build-windows:
    name: Windows VS2019
    runs-on: windows-latest
    env:
      HAS_OPENSSL_BUILD: 0
      CC: gcc
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          choco install make nasm zip iasl --no-progress

      - name: CI Bootstrap
        run: |
          src=$(curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - run: ./build_duet.tool
      - run: ./build_oc.tool

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Artifacts
          path: Binaries/*.zip
